version: 0.2

phases:
  pre_build:
    commands:
      - cd MyLambdaFunction/src/MyLambdaFunction
      - pwd
  build:
    commands:
      - |
        rm /codebuild/global.json -f
        sam build
  post_build:
    commands:
      - |
        sam deploy --stack-name ${STACK_NAME} \
          --parameter-overrides Environment=${ENVIRONMENT} \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --config-env ${ENVIRONMENT} \
          --resolve-s3 

