version: 0.2

phases:
  pre_build:
    commands:
      - cd MyLambdaFunction/src/MyLambdaFunction
      - pwd
      - echo ${STACK_NAME}
      - echo ${Environment}
      - echo ${S3_BUCKET}
  build:
    commands:
      - |
        rm /codebuild/global.json -f
        sam build
  post_build:
    commands:
      - |
        sam deploy --stack-name ${STACK_NAME} \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --s3-bucket ${S3_BUCKET} \
          --capabilities CAPABILITY_IAM
